import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// The workout timer's cue: a single soft 1 s chime that plays only when
/// a rest ends, so the user can keep their eyes off the phone mid-workout.
///
/// The beep is generated by `tool/gen_workout_beeps.py` rather than sampled —
/// a few dozen KB of PCM, with no licence attached.
///
/// Nothing here ever throws: a workout that cannot play a sound is a workout
/// that runs quietly, not one that falls over. That matters most on web, where
/// the browser blocks audio until the page has been interacted with — the
/// first cue can be swallowed and every later one still plays.
final workoutSoundsProvider = Provider<WorkoutSounds>((ref) {
  final sounds = WorkoutSounds();
  ref.onDispose(sounds.dispose);
  return sounds;
});

class WorkoutSounds {
  static const _file = 'sounds/workout_beep.wav';

  /// The beep mixes with other audio instead of grabbing focus: on Android
  /// this requests no audio focus, on iOS it sets the mixWithOthers session
  /// option — Spotify, YouTube Music, etc. keep playing underneath the beep.
  static final _mixingContext = AudioContextConfig(
    focus: AudioContextConfigFocus.mixWithOthers,
  ).build();

  /// Kept for the app's life: a player that already holds its source starts
  /// on the next frame instead of after a decode.
  AudioPlayer? _player;

  bool muted = false;

  /// Plays the rest-over beep, or does nothing if the audio stack is
  /// unavailable.
  ///
  /// Deliberately not awaited by callers — a cue is feedback, and the timer
  /// it acknowledges should not wait on a decoder.
  void playRestOver() {
    if (muted) return;
    unawaited(_play());
  }

  Future<void> _play() async {
    try {
      var player = _player;
      if (player == null) {
        player = AudioPlayer();
        await player.setReleaseMode(ReleaseMode.stop);
        // Set before the first play so the beep never grabs audio focus and
        // pauses music the user already has going in another app.
        await player.setAudioContext(_mixingContext);
        _player = player;
      }
      // Rewound rather than restarted: a player left at the end of its source
      // is silent.
      await player.stop();
      await player.play(AssetSource(_file), volume: 0.9);
    } catch (error) {
      // A missing asset, a browser that has not been tapped yet, a platform
      // with no audio: none of it is worth interrupting a workout for.
      debugPrint('[sounds] restOver failed: $error');
    }
  }

  void dispose() {
    _player?.dispose();
    _player = null;
  }
}
