import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// The workout timer's cues: a blip when a set goes down, a rising pair when
/// the workout starts, three when the rest is over, a fanfare at the end.
///
/// The point is being able to keep your eyes off the phone mid-set, so the
/// four are deliberately distinguishable by ear alone. They are generated by
/// `tool/gen_workout_beeps.py` rather than sampled — a few KB of PCM each,
/// with no licence attached.
///
/// Nothing here ever throws: a workout that cannot play a sound is a workout
/// that runs quietly, not one that falls over. That matters most on web, where
/// the browser blocks audio until the page has been interacted with — the
/// first cue can be swallowed and every later one still plays.
final workoutSoundsProvider = Provider<WorkoutSounds>((ref) {
  final sounds = WorkoutSounds();
  ref.onDispose(sounds.dispose);
  return sounds;
});

enum WorkoutCue { start, setDone, restOver, workoutDone }

class WorkoutSounds {
  static const _files = {
    WorkoutCue.start: 'sounds/workout_start.wav',
    WorkoutCue.setDone: 'sounds/set_done.wav',
    WorkoutCue.restOver: 'sounds/rest_over.wav',
    WorkoutCue.workoutDone: 'sounds/workout_done.wav',
  };

  /// One player per cue, kept for the app's life: they are a few KB each, and
  /// a player that already holds its source starts on the next frame instead
  /// of after a decode.
  final _players = <WorkoutCue, AudioPlayer>{};

  bool muted = false;

  /// Plays [cue], or does nothing if the audio stack is unavailable.
  ///
  /// Deliberately not awaited by callers — a cue is feedback, and the set it
  /// acknowledges should not wait on a decoder.
  void play(WorkoutCue cue) {
    if (muted) return;
    unawaited(_play(cue));
  }

  Future<void> _play(WorkoutCue cue) async {
    try {
      var player = _players[cue];
      if (player == null) {
        player = AudioPlayer();
        await player.setReleaseMode(ReleaseMode.stop);
        _players[cue] = player;
      }
      // Rewound rather than restarted: two sets ticked off in quick succession
      // should beep twice, and a player left at the end of its source is silent.
      await player.stop();
      await player.play(AssetSource(_files[cue]!), volume: 0.9);
    } catch (error) {
      // A missing asset, a browser that has not been tapped yet, a platform
      // with no audio: none of it is worth interrupting a workout for.
      debugPrint('[sounds] $cue failed: $error');
    }
  }

  void dispose() {
    for (final player in _players.values) {
      player.dispose();
    }
    _players.clear();
  }
}
