export const DELETE_USER_DATA = 'DELETE_USER_DATA';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const RESET_STATE = 'RESET_STATE';
export const UPDATE_STATE = 'UPDATE_STATE';
